### ISSUE TITLE
Starting diamond service is frequently timing out

### ISSUE THREAD

**Issue by adammeghji** [damm/diamond#18]
We're experiencing issues with this cookbook's diamond service timing out on launch, via Ubuntu 14.04 LTS.  Happens intermittently across re-runs.

It seems there's a 8 second timeout somewhere.  Runit has a default 7 second timeout, for what it's worth.

Error snippet:
```
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/sv restart /etc/service/diamond ----
STDOUT: timeout: run: /etc/service/diamond: (pid 15129) 8s, got TERM
STDERR:
---- End output of /usr/bin/sv restart /etc/service/diamond ----
Ran /usr/bin/sv restart /etc/service/diamond returned 1
```

Any insight re: what's happening?  We're totally stumped, but any clues and we'll happily troubleshoot and try to issue a bugfix PR.

Full error output:
```
[2015-10-05T20:26:29+00:00] INFO: runit_service[diamond] enabled

================================================================================
Error executing action `enable` on resource 'runit_service[diamond]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /usr/bin/sv restart /etc/service/diamond ----
STDOUT: timeout: run: /etc/service/diamond: (pid 15129) 8s, got TERM
STDERR:
---- End output of /usr/bin/sv restart /etc/service/diamond ----
Ran /usr/bin/sv restart /etc/service/diamond returned 1

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:184:in `restart_service'
/var/chef/cache/cookbooks/runit/libraries/provider_runit_service.rb:85:in `action_enable'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/diamond/providers/configure.rb

 75:   runit_service new_resource.runit_name do
 76:     run_template_name "diamond"
 77:     cookbook new_resource.cookbook
 78:     default_logger true
 79:     options({
 80:               :prefix => new_resource.prefix
 81:             })
 82:   end
 83:   new_resource.updated_by_last_action(true)

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/diamond/providers/configure.rb:75:in `block in class_from_file'

runit_service("diamond") do
  provider Chef::Provider::Service::Runit
  action :enable
  updated true
  updated_by_last_action true
  supports {:restart=>true, :reload=>true, :status=>true}
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  service_name "diamond"
  enabled true
  pattern "diamond"
  status_command "/usr/bin/sv status /etc/service"
  sv_bin "/usr/bin/sv"
  sv_dir "/etc/sv"
  service_dir "/etc/service"
  lsb_init_dir "/etc/init.d"
  options {:prefix=>"/opt/diamond"}
  log true
  cookbook "diamond"
  default_logger true
  restart_on_update true
  run_template_name "diamond"
  log_template_name "diamond"
  check_script_template_name "diamond"
  finish_script_template_name "diamond"
  sv_templates true
  service_mirror # Declared in

service("diamond") do
  provider Chef::Provider::Service::Simple
  action [:nothing]
  supports {:restart=>true, :reload=>true, :status=>true}
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  service_name "diamond"
  pattern "diamond"
  start_command "/usr/bin/sv start /etc/service/diamond"
  stop_command "/usr/bin/sv stop /etc/service/diamond"
  status_command "/usr/bin/sv status /etc/service/diamond"
  restart_command "/usr/bin/sv restart /etc/service/diamond"
end

  declared_type :runit_service
  cookbook_name "unii-diamond"
end
```

**Comment by damm** [comment]
Likely things are just a bit slow in the startup; so maybe we should apply `sv_timeout` to higher than 7?

**Comment by adammeghji** [comment]
That would be ideal -- in our case, we'd likely set a fairly high value like `30 seconds` just to be safe.

**Comment by damm** [comment]
I was thinking 45 seconds actually; mind taking a look at the branch called timeout and seeing if that works for you?

**Comment by adammeghji** [comment]
That works perfectly for me!  I'd be fine with overriding the default 7s value as an attribute as well (we're using a wrapper cookbook anyhow), if that makes for a cleaner change.  Otherwise, 45s is great, and will make the operation more resilient for everyone (up to you).

**Comment by damm** [comment]
I like 45s; but I agree it should be tuneable.  I pushed that into master so I hope everything should work better for you now.

Thank you for reporting the issue.
